name: On Push hook

 

on:

  push:

    branches:

      - '*'

      - '*/*'

      - '**'

      - '!prd'

      - '!qa'

 

permissions:

  id-token: write

  contents: read

 

jobs:

  validate_branch_name:

    runs-on: ubuntu-latest

    steps:

      - uses: deepakputhraya/action-branch-name@master

        with:

          regex: '[a-z]'

          ignore: prd

